name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  lowest-version-tests:
    name: Build lowest version
    runs-on: ubuntu-latest

    steps:
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: bcmath, gmp, intl, dom, mbstring

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download dependencies
      run: composer update --prefer-stable --prefer-dist --no-interaction --no-progress --no-suggest --prefer-lowest --classmap-authoritative

    - name: Run tests
      run: composer run-script test

  tests:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 8.1
          - 8.2
          - 8.3
          - 8.4

    steps:
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: bcmath, gmp, intl, dom, mbstring
        ini-values: zend.assertions=1

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --classmap-authoritative

    - name: Run tests
      run: composer test

  psalm:
    name: Psalm
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: bcmath, gmp, intl, dom, mbstring

    - name: Download dependencies
      run: composer install --classmap-authoritative

    - name: Psalm
      run: vendor/bin/psalm
